spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            first:  #数据源1
                url: jdbc:mysql://localhost:3306/framework?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&tinyInt1isBit=true
                username: root
                password: 123456
                initial-size: 5
                max-active: 10
                min-idle: 5
                max-wait: 60000
                pool-prepared-statements: true
                max-pool-prepared-statement-per-connection-size: 20
                time-between-eviction-runs-millis: 60000
                min-evictable-idle-time-millis: 300000
                validation-query: SELECT 1 FROM DUAL
                test-while-idle: true
                test-on-borrow: false
                test-on-return: false
                stat-view-servlet:
                    enabled: true
                    url-pattern: /druid/*
                    #login-username: admin
                    #login-password: admin
                filter:
                    stat:
                        log-slow-sql: true
                        slow-sql-millis: 1000
                        merge-sql: true
                    wall:
                        config:
                          multi-statement-allow: true
            second:  #数据源2
                url: jdbc:mysql://localhost:3306/framework?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&tinyInt1isBit=true
                username: root
                password: 123456
                initial-size: 5
                max-active: 10
                min-idle: 5
                max-wait: 60000
                pool-prepared-statements: true
                max-pool-prepared-statement-per-connection-size: 20
                time-between-eviction-runs-millis: 60000
                min-evictable-idle-time-millis: 300000
                validation-query: SELECT 1 FROM DUAL
                test-while-idle: true
                test-on-borrow: false
                test-on-return: false
                stat-view-servlet:
                    enabled: true
                    url-pattern: /druid/*
                    #login-username: admin
                    #login-password: admin
                filter:
                    stat:
                        log-slow-sql: true
                        slow-sql-millis: 1000
                        merge-sql: true
                    wall:
                        config:
                          multi-statement-allow: true
#redis配置
    redis:
        # REDIS (RedisProperties)
        # Redis数据库索引（默认为0）
        database: 0
        host: localhost          # Redis服务器地址
        port: 6379                   # Redis服务器连接端口
        password:                    # Redis服务器连接密码（默认为空）
        jedis:
            pool:
                max-active: 8          # 连接池最大连接数（使用负值表示没有限制）
                max-idle: 8            # 连接池中的最大空闲连接
                max-wait: -1ms         # 连接池最大阻塞等待时间（使用负值表示没有限制）
                min-idle: 5            # 连接池中的最小空闲连接
#        lettuce:
#            pool:
#                max-active: 8          # 连接池最大连接数（使用负值表示没有限制）
#                max-idle: 8            # 连接池中的最大空闲连接
#                max-wait: -1ms         # 连接池最大阻塞等待时间（使用负值表示没有限制）
#                min-idle: 5            # 连接池中的最小空闲连接
    rabbitmq:
        host: localhost
        port: 5672
        username: test
        password: test123
        publisher-confirms: true
        publisher-returns: true
        template:
            mandatory: true

#应用自定义配置
application:
    #权限安全配置
    security:
         # Token 有效时间，单位秒
         tokenExpire: 86400
         # 客户默认初始密码
         defaultPassword: 123456
         # 营销中心业务员角色id
         roleId: 32
         # 营销中心部门id
         deptId: 6
         # 默认管理员id,多个用逗号分隔
         adminIds: 1

#热部署配置
devtools:
    livereload:
      enabled: true
    restart:
        enabled: true
        additional-exclude: views/**